# Generated by Django 5.2.8 on 2025-11-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista Tributario'), ('editor', 'Usuario Autorizado (Editor)'), ('auditor', 'Auditor')], default='analista', max_length=20),
        ),
    ]
