# Generated by Django 5.2.8 on 2025-12-11 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador'), ('analista', 'Analista Tributario'), ('editor', 'Usuario Autorizado (Editor)'), ('auditor', 'Auditor'), ('corredor', 'Corredor de Bolsa')], default='analista', max_length=20),
        ),
    ]
