# Generated by Django 5.2.8 on 2025-12-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrador General'), ('tributario', 'Administrador Tributario'), ('auditor', 'Auditor Interno'), ('corredor', 'Corredor de Bolsa')], default='tributario', max_length=20),
        ),
    ]
