# Generated by Django 5.2.8 on 2025-11-27 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(db_index=True, max_length=12)),
                ('dv', models.CharField(blank=True, max_length=1, null=True)),
                ('razon_social', models.CharField(max_length=255)),
                ('regimen_tributario', models.CharField(blank=True, max_length=100, null=True)),
                ('capital_propio_tributario', models.BigIntegerField(blank=True, null=True)),
                ('inicio_actividades', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'empresas',
            },
        ),
        migrations.CreateModel(
            name='ArchivoCargado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta', models.CharField(blank=True, max_length=1024, null=True)),
                ('cargado_en', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
                ('cargado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='archivos', to='calificaciones.empresa')),
            ],
            options={
                'db_table': 'archivos_cargados',
            },
        ),
        migrations.CreateModel(
            name='CalificacionTributaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('tipo', models.CharField(choices=[('retiro', 'retiro'), ('remesa', 'remesa'), ('dividendo', 'dividendo')], max_length=20)),
                ('monto_original', models.BigIntegerField()),
                ('monto_reajustado', models.BigIntegerField(blank=True, null=True)),
                ('imputacion', models.CharField(blank=True, max_length=50, null=True)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('estado', models.CharField(db_index=True, default='vigente', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('archivo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='calificaciones.archivocargado')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='calificaciones.empresa')),
            ],
            options={
                'db_table': 'calificaciones_tributarias',
            },
        ),
        migrations.CreateModel(
            name='CreditoIDPC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(blank=True, max_length=100, null=True)),
                ('monto', models.BigIntegerField()),
                ('ejercicio', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('calificacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creditos', to='calificaciones.calificaciontributaria')),
            ],
            options={
                'db_table': 'creditos_idpc',
            },
        ),
        migrations.CreateModel(
            name='Propietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(db_index=True, max_length=12)),
                ('dv', models.CharField(blank=True, max_length=1, null=True)),
                ('nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('calidad', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='propietarios', to='calificaciones.empresa')),
            ],
            options={
                'db_table': 'propietarios',
            },
        ),
        migrations.AddField(
            model_name='calificaciontributaria',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificaciones', to='calificaciones.propietario'),
        ),
        migrations.CreateModel(
            name='AccionesPropietario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acciones', models.BigIntegerField(blank=True, null=True)),
                ('fecha', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones', to='calificaciones.propietario')),
            ],
            options={
                'db_table': 'acciones_propietarios',
            },
        ),
        migrations.CreateModel(
            name='RegistroEmpresarial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('RAI', 'RAI'), ('DDAN', 'DDAN'), ('REX', 'REX'), ('RAP', 'RAP'), ('INR', 'INR'), ('SAC', 'SAC')], max_length=20)),
                ('saldo_inicial', models.BigIntegerField(blank=True, null=True)),
                ('saldo_final', models.BigIntegerField(blank=True, null=True)),
                ('ejercicio', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='calificaciones.empresa')),
            ],
            options={
                'db_table': 'registros_empresariales',
            },
        ),
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=50)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('entidad', models.CharField(max_length=100)),
                ('entidad_id', models.BigIntegerField(blank=True, null=True)),
                ('detalle', models.JSONField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'auditoria',
                'indexes': [models.Index(fields=['entidad', 'entidad_id'], name='auditoria_entidad_9c3bf7_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='propietario',
            index=models.Index(fields=['rut'], name='propietario_rut_8383cd_idx'),
        ),
        migrations.AddIndex(
            model_name='calificaciontributaria',
            index=models.Index(fields=['empresa', 'propietario', 'fecha'], name='calificacio_empresa_62189e_idx'),
        ),
        migrations.AddIndex(
            model_name='calificaciontributaria',
            index=models.Index(fields=['tipo', 'imputacion'], name='calificacio_tipo_6bd40d_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='registroempresarial',
            unique_together={('empresa', 'tipo', 'ejercicio')},
        ),
    ]
