# Generated by Django 5.2.8 on 2025-11-28 00:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado70',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio_comercial', models.PositiveIntegerField()),
                ('fecha_emision', models.DateField(auto_now_add=True)),
                ('folio', models.PositiveIntegerField(blank=True, null=True)),
                ('totales', models.JSONField(default=dict)),
                ('detalles', models.JSONField(default=list)),
                ('archivo_pdf', models.CharField(blank=True, max_length=1024, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='calificaciones.empresa')),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='calificaciones.propietario')),
            ],
            options={
                'db_table': 'certificados70',
                'unique_together': {('empresa', 'propietario', 'anio_comercial')},
            },
        ),
    ]
