# Generated by Django 5.2.8 on 2025-11-28 02:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0002_certificado70'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='tipo_sociedad',
            field=models.CharField(blank=True, choices=[('Ltda', 'Limitada'), ('EIRL', 'EIRL'), ('SpA', 'SpA'), ('SA', 'S.A.')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='total_acciones',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='valor_nominal',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AddField(
            model_name='propietario',
            name='porcentaje_participacion',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='Accion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_acciones', models.BigIntegerField()),
                ('valor_nominal', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('tipo_propiedad', models.CharField(choices=[('pleno', 'Pleno Propietario'), ('nudo', 'Nudo Propietario'), ('usufructo', 'Usufructuario')], default='pleno', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_emitidas', to='calificaciones.empresa')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acciones_poseidas', to='calificaciones.propietario')),
            ],
            options={
                'db_table': 'acciones',
            },
        ),
        migrations.DeleteModel(
            name='AccionesPropietario',
        ),
    ]
