# Generated by Django 5.2.8 on 2025-12-11 01:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0003_empresa_tipo_sociedad_empresa_total_acciones_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Corredor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(db_index=True, max_length=12)),
                ('empresa_corredora', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('empresas', models.ManyToManyField(blank=True, related_name='corredores', to='calificaciones.empresa')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='corredor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'corredores',
            },
        ),
    ]
