# Generated by Django 5.2.8 on 2025-12-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calificaciones', '0004_corredor'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciontributaria',
            name='observaciones_analista',
            field=models.TextField(blank=True, null=True),
        ),
    ]
